'use client';

// =============================================================================
// Reports View — daily/weekly/monthly energy reports (brief §66, §96)
// -----------------------------------------------------------------------------
// Reports are GENERATED by GAS from persisted telemetry, NOT computed on the
// ESP32. The PWA sends a report request to /api/reports with range + from/to,
// and the ESP32 returns either:
//   1. Cached daily aggregates (computed periodically by ESP32)
//   2. An error indicating the range is not yet aggregated
//
// Each DailyEnergyRecord contains:
//   date, chargeWh, dischargeWh, netWh, chargeAh, dischargeAh,
//   peakChargeA, peakDischargeA, socMin, socMax, alarmCount,
//   telemetryCompleteness (0..1), deviceAvailability (0..1)
// =============================================================================

import { useState } from 'react';
import { api } from '@/lib/api';
import { useLanguage } from '@/components/providers/language-provider';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { FileText, Download, RefreshCw } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { fmtWh, fmtAh, fmtPct } from '@/lib/format';
import { toast } from 'sonner';
import type { ReportRange, DailyEnergyRecord } from '@/lib/types';

const RANGES: { value: ReportRange; labelKey: string; days: number }[] = [
  { value: 'daily', labelKey: 'reports.range_daily', days: 7 },
  { value: 'weekly', labelKey: 'reports.range_weekly', days: 28 },
  { value: 'monthly', labelKey: 'reports.range_monthly', days: 90 },
];

function startOfDay(d: Date): Date {
  const r = new Date(d);
  r.setHours(0, 0, 0, 0);
  return r;
}

export function ReportsView() {
  const { t } = useLanguage();
  const [range, setRange] = useState<ReportRange>('daily');
  const now = new Date();
  const days = RANGES.find((r) => r.value === range)?.days ?? 7;
  const to = startOfDay(now).getTime();
  const from = to - days * 24 * 3600 * 1000;

  const { data, isLoading, isFetching, refetch } = useQuery({
    queryKey: ['reports', range, from, to],
    queryFn: () => api.reports({ range, from, to, format: 'json' }),
    staleTime: 5 * 60_000,  // 5 min
  });

  const records: DailyEnergyRecord[] = data?.records ?? [];

  const exportCsv = () => {
    if (records.length === 0) {
      toast.error('No records to export');
      return;
    }
    const headers = [
      'date', 'chargeWh', 'dischargeWh', 'netWh',
      'chargeAh', 'dischargeAh',
      'peakChargeA', 'peakDischargeA',
      'socMin', 'socMax', 'alarmCount',
      'telemetryCompleteness', 'deviceAvailability',
    ];
    const rows = records.map((r) => [
      r.date,
      r.chargeWh, r.dischargeWh, r.netWh,
      r.chargeAh, r.dischargeAh,
      r.peakChargeA ?? '', r.peakDischargeA ?? '',
      r.socMin ?? '', r.socMax ?? '',
      r.alarmCount,
      r.telemetryCompleteness,
      r.deviceAvailability,
    ]);
    const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `plts-report-${range}-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Exported ${records.length} records`);
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-12 w-64" />
        <Skeleton className="h-16 rounded-xl" />
        <Skeleton className="h-96 rounded-xl" />
      </div>
    );
  }

  // Aggregate totals
  const totals = records.reduce(
    (acc, r) => {
      acc.chargeWh += r.chargeWh;
      acc.dischargeWh += r.dischargeWh;
      acc.chargeAh += r.chargeAh;
      acc.dischargeAh += r.dischargeAh;
      acc.alarmCount += r.alarmCount;
      acc.completenessSum += r.telemetryCompleteness;
      acc.availabilitySum += r.deviceAvailability;
      return acc;
    },
    { chargeWh: 0, dischargeWh: 0, chargeAh: 0, dischargeAh: 0,
      alarmCount: 0, completenessSum: 0, availabilitySum: 0 },
  );
  const avgCompleteness = records.length > 0 ? totals.completenessSum / records.length : 0;
  const avgAvailability = records.length > 0 ? totals.availabilitySum / records.length : 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <FileText className="w-6 h-6 text-primary" />
          {t('reports.title')}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">{t('reports.subtitle')}</p>
      </div>

      {/* Range selector */}
      <Card className="border-border/60">
        <CardContent className="p-3 flex items-center gap-3 flex-wrap">
          <span className="text-xs text-muted-foreground uppercase tracking-wider">
            Range:
          </span>
          <div className="flex gap-1">
            {RANGES.map((r) => (
              <Button
                key={r.value}
                variant={range === r.value ? 'default' : 'outline'}
                size="sm"
                onClick={() => setRange(r.value)}
              >
                {t(r.labelKey as never)}
              </Button>
            ))}
          </div>
          <div className="ml-auto flex gap-2">
            <Button
              variant="outline" size="sm"
              onClick={() => refetch()}
              disabled={isFetching}
            >
              <RefreshCw className={`w-3 h-3 mr-1 ${isFetching ? 'animate-spin' : ''}`} />
              {t('common.refresh')}
            </Button>
            <Button variant="outline" size="sm" onClick={exportCsv}>
              <Download className="w-3 h-3 mr-1" />
              CSV
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Aggregate summary */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <Card className="border-border/60 bg-status-on/5">
          <CardContent className="p-3">
            <div className="text-[10px] text-muted-foreground uppercase">Charge</div>
            <div className="text-lg font-mono font-bold text-status-on">
              {fmtWh(totals.chargeWh)}
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/60 bg-status-warn/5">
          <CardContent className="p-3">
            <div className="text-[10px] text-muted-foreground uppercase">Discharge</div>
            <div className="text-lg font-mono font-bold text-status-warn">
              {fmtWh(totals.dischargeWh)}
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/60">
          <CardContent className="p-3">
            <div className="text-[10px] text-muted-foreground uppercase">Net</div>
            <div className="text-lg font-mono font-bold">
              {fmtWh(totals.chargeWh - totals.dischargeWh)}
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/60">
          <CardContent className="p-3">
            <div className="text-[10px] text-muted-foreground uppercase">
              {t('reports.telemetry_completeness')}
            </div>
            <div className="text-lg font-mono font-bold">
              {fmtPct(avgCompleteness * 100)}
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/60">
          <CardContent className="p-3">
            <div className="text-[10px] text-muted-foreground uppercase">
              {t('reports.device_availability')}
            </div>
            <div className="text-lg font-mono font-bold">
              {fmtPct(avgAvailability * 100)}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Daily records table */}
      <Card className="border-border/60">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm flex items-center gap-2">
            <FileText className="w-4 h-4 text-primary" />
            Daily records ({records.length} days)
          </CardTitle>
          <CardDescription className="text-xs">
            Aggregated from ESP32-persisted telemetry. Lower completeness → less reliable aggregates.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {records.length === 0 ? (
            <div className="py-12 text-center text-muted-foreground text-sm">
              {t('reports.empty')}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead className="text-right">Charge</TableHead>
                    <TableHead className="text-right">Discharge</TableHead>
                    <TableHead className="text-right">Net</TableHead>
                    <TableHead className="text-right">SOC min/max</TableHead>
                    <TableHead className="text-right">Peak A</TableHead>
                    <TableHead className="text-center">Alarms</TableHead>
                    <TableHead className="text-right">Completeness</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {records.map((r) => (
                    <TableRow key={r.date}>
                      <TableCell className="font-mono text-xs">{r.date}</TableCell>
                      <TableCell className="text-right font-mono text-xs text-status-on">
                        {fmtWh(r.chargeWh)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-xs text-status-warn">
                        {fmtWh(r.dischargeWh)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-xs">
                        {fmtWh(r.netWh)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-xs">
                        {r.socMin != null && r.socMax != null
                          ? `${r.socMin.toFixed(0)}–${r.socMax.toFixed(0)}%`
                          : '—'}
                      </TableCell>
                      <TableCell className="text-right font-mono text-xs">
                        {r.peakChargeA != null ? `↑${r.peakChargeA.toFixed(1)}A` : ''}
                        {r.peakDischargeA != null ? ` ↓${r.peakDischargeA.toFixed(1)}A` : ''}
                      </TableCell>
                      <TableCell className="text-center">
                        {r.alarmCount > 0 ? (
                          <Badge variant="outline" className="text-[9px] border-status-warn/30 text-status-warn">
                            {r.alarmCount}
                          </Badge>
                        ) : (
                          <span className="text-muted-foreground">—</span>
                        )}
                      </TableCell>
                      <TableCell className="text-right">
                        <Badge
                          variant="outline"
                          className={
                            r.telemetryCompleteness >= 0.95
                              ? 'text-[9px] border-status-on/30 text-status-on'
                              : r.telemetryCompleteness >= 0.8
                                ? 'text-[9px] border-status-warn/30 text-status-warn'
                                : 'text-[9px] border-status-error/30 text-status-error'
                          }
                        >
                          {fmtPct(r.telemetryCompleteness * 100)}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
